### ISSUE TITLE
Should not create the empty noso-2m.log file when it's only reporting version

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#12]
Hey @f04ever,

I've noticed that when running:
```console
$ ./noso-2m --version
```
An empty log file is created.

I'm of the opinion that when ever the `--version` flag is present, event if there are others, it should always report the version and then exit.
This would imply that the log is not created.

What's your opinion?

Cheers,
Gus

**Comment by f04ever** [comment]
I've got. A fix will be released soon!
Cheers,

**Comment by f04ever** [comment]
Fix released
