### ISSUE TITLE
Core Dump solved by deleting hint_nodes.txt

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#14]
Hey @f04ever,

Sometimes the app dumps the core when accessing the net when it already has a past `hint_nodes.txt` file.
I'm sorry that it's so vague, but when I do have those core dumps, I delete the `hint_nodes.txt` file and the app runs again OK after creating a new `hint_nodes.txt` file.

Cheers,
Gus

**Comment by f04ever** [comment]
Node relating has been completely removed from the commit f0d47917c8081fbfafdb71111557ba93dfe53dd4 as solo mining is not more supported
