### ISSUE TITLE
How can I have DEBUG output on the log file?

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#15]
Hey @f04ever,

The `noso-2m.log` does not contain any DEBUG data and when I use `-DDEBUG` it clashes with:
> file: logging.hpp
```cpp
enum class CLogLevel { FATAL, ERROR, WARN, INFO, -->DEBUG<--, };
```

You do not log much. Not even the accepted/rejected/failed shares.

So how can I turn on DEBUG?

Cheers,
Gus

**Comment by f04ever** [comment]
Hi,
`enum class CLogLevel { FATAL, ERROR, WARN, INFO, -->DEBUG<--, };` defines the logging levels. These levels are not relating to -DDEBUG / -DNDEBUG directives in the C/C++.

You can build the debugging version of noso-2m by this command:

`clang++ noso-2m.cpp inet.cpp comm.cpp util.cpp tool.cpp misc.cpp caches.cpp mining.cpp hashing.cpp md5-c.cpp -o noso-2m -std=c++20  -g0 -Wall --stdlib=libc++ -lpthread -lncurses -lform -ltermcap`

(remove the options `-DNDEBUG -Ofast` and add `-g0`)

For logging message (in TEXTUI/NCURSES mode). There is actually a bug. It does not output all logging messages to file noso-2m.log. I will fix it next releases.

From the commit `597be40e7976a0d05d32259a85cc8465c862cb8a`, if you build with option `-DNO_TEXTUI`, the option `-ldebug` when launch noso-2m should output more logging message at debug level.
Remember, this commit is a beta version, TEXTUI mode is still very weird. So NO_TEXTUI mode would better.

Best!
