### ISSUE TITLE
Minning process needs to stop at 57 accepted

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#16]
Hey @f04ever,

You need to have the mining process stop at 57 accepted shares.
You also need to correctly process the pool message that states that the pool has accepted 57 shares.

I had try at doing the stop after 57 accepted but I failed miserably :smile: !!

Cheers,
Gus

**Comment by f04ever** [comment]
Hey Gus,
PoPW early compatible at commit 597be40e7976a0d05d32259a85cc8465c862cb8a .
Build yourself with option -DNO_TEXTUI (because the TEXTUI not upgraded yet).
Check noso-2m-SAMPLE.cfg for config changes.
Cheers!
