### ISSUE TITLE
Add support password

### ISSUE THREAD

**Issue by lhllhx** [f04ever/noso-2m#19]
Add support password. now you have to add password  to mine

**Comment by f04ever** [comment]
Currently noso-2m is still working well without password. I will add support password when network requires mandatorily.

**Comment by lhllhx** [comment]
ok I will reopen it when it requires

**Comment by lhllhx** [comment]
password is from now MANDATORY.

**Comment by f04ever** [comment]
There is no update on noso project's repository from latest announcement.
noso-2m is still working well without password.
