### ISSUE TITLE
Miner does not saturate my CPU

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#2]
Hey @f04ever,

I have a 1 core 2 threads CPU(Yeah, really crappy :) ) and the miner does not seem to saturate the 2nd thread.

It makes one of the threads be 100% most of the time but the other thread is barely tickled, I think.

Is this intentional?

Cheers,
Gus

**Comment by f04ever** [comment]
As design, noso-2m uses 1 thread dedicating for network communication, like doing consensus nodes, fetch pool information, submit solutions or pool shares... the rest threads are for hashing. The communicating thread is almost free, while other threads are at 100% most the time.
To burn all threads, you can set THREADCOUNT+1, the communicating thread will share resource with others. Total hashrate will increase, the average hashrate per thread reduce (as resource competition btw threads), and the computer be burned totally. I do not recommend using this case, :-) cheer!

**Comment by gcarreno** [comment]
Hey @f04ever,

Humm, quite an interesting choice. Interesting because yours is the only miner I know that fully dedicates one full thread to comms.

It kinda makes sense when you have 4, 6, 8 cores with 2 threads each and you then have a good amount of hashing power.
I guess my `1core2thread` crappy CPU is the odd one out.

Ok, MANY thanks for the explanation!! This completely explains it all :)

Cheers,
Gus
