### ISSUE TITLE
Cannot exit from an infinite while loop on bash

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#3]
Hey @f04ever,

If one surrounds the binary with an infinite loop, like so:

```sh
while true
do
    noso-2m ....
done
```

It's nigh impossible to exit the bash script with `CTRL+C`.

The last time I tried it I had to `kill -9` the parent `bash` process and then had to `kill -9` the `noso-2m` cuz it didn't die when the parent was killed. Resilient bastard :smile: 

Cheers,
Gus

**Comment by f04ever** [comment]
Let me find a better solution if any, may take a low priority. Tks!

**Comment by f04ever** [comment]
may integrate with exit code 0 is normal, otherwise failure
