### ISSUE TITLE
Ocasional race condition when switching block

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#4]
Hey @f04ever,

I've been noticing, more than 5 times by my count, that the new version of `noso-2m` will get stuck when transitioning from one block to the other.

The last info it shows is the Summary, and that's it.

The _Waiting for block_ never shows up

Cheers,
Gus

**Comment by f04ever** [comment]
Hi, it is fixed in v0.2.0!
Cheers!

**Comment by gcarreno** [comment]
Hey @f04ever,

Many, many thanks mate!!

Cheers,
Gus
