### ISSUE TITLE
Core dump when pressing CTRL+C on connection failure

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#5]
Hey @f04ever,

Looks like there's something going boom:
```
getsockopt/socket failed: Operation now in progress
1650425912(512))WAITING TARGET FROM POOL Ravi (Retry 4/5)
getsockopt/socket failed: Operation now in progress
1650425915(515))WAITING TARGET FROM POOL Ravi (Retry 5/5)
1650425915(515))NO REDUNDANT POOL FOR FAILOVER. MAKE ANOTHER ATTEMPT!
getsockopt/socket failed: Operation now in progress
1650425918(518))WAITING TARGET FROM POOL Ravi (Retry 1/5)
^C
Ctrl+C pressed! Wait for finishing all threads...
getsockopt/socket failed: Operation now in progress
./noso-2m.sh: line 10: 397002 Segmentation fault      (core dumped)
```

Really sorry I can't give you more info :frowning_face: 

Cheers,
Gus

**Comment by f04ever** [comment]
Hi,

Segmentation fault (core dumped) during Ctrl+C interruption is taking consideration. Currently it does not effect hashing.

The errors like "getsockopt/socket failed: Operation now in progress" is not belong to the error, and just for debug information. They can be ignored by append the shell redirection `2>errors.txt` to the end of running command.

Thank you for reporting!

Cheers!

**Comment by gcarreno** [comment]
Hey @f04ever,

While I do agree that this issue does not impair the mining code, I do not agree that it's not important.

A Segmentation fault is when you try to access memory that you can't, like a freed object or buffer under/over flow.
And I'm quite sure that you're quite familiar with the bad reputation that C/C++ code has due to programmers messing up exactly what I mentioned above, right?

Yes it will not make miners unhappy due to not being able to mine, but it will maybe keep the bad actors happy that your software is maybe hackable. And I'm betting that some idiot miners are running `noso-2m` with elevated privileges.

Wouldn't you agree?

Cheers,
Gus

**Comment by f04ever** [comment]
Hey! I didn't say it is not important. It is being considered.
I actually know why and how it happen, and need to determine where it occurs. That are some pieces of codes do not catch the exit situation in time as they should be, they continue their normal works while the context has been cleanup for exit by other threads. I need time to reproduce the situations to find out where it actually happen. That is a difficult debugging, especially in concurrent context. In my all systems seem not occur that kind of errors at all, so it also makes some difficulty to debug as well.
Cheers!

**Comment by gcarreno** [comment]
Hey @f04ever,

Ok, ok, I'm sorry, maybe I came a bit too strong :smile: 

I'll leave you at it, but funny enough I get the Segmentation fault a lot under Linux 64b

Maybe that's a Linux only thing?

Cheers,
Gus

**Comment by f04ever** [comment]
TextUI with command exit may be an approach
