### ISSUE TITLE
Without human intervention win64 miner cannot connect to pool

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#6]
Hey @f04ever,

For some unknown reason win64 versions of the software are now completely unable to connect to a pool as shown in the following image:
![noso-2m-error-win64](https://user-images.githubusercontent.com/81799/164385937-e9b9738c-3810-49a6-9cb5-e8864d41e3a5.png)

The Windows machine hosting the pool has a miner that can't even connect to itself.

**Edit**: They can still mine solo. But they cannot mine to any pool. We even tried `devnoso`

We have 6 Linux 64b machines that are having no issues connecting to the pool.

Is it a situation with to low of an integer?

Cheers,
Gus

**Comment by f04ever** [comment]
Fixed!
