### ISSUE TITLE
Fatal error: 'map' file not found

### ISSUE THREAD

**Issue by gcarreno** [f04ever/noso-2m#8]
Hey @f04ever,

If I remove the option `-fuse-ld=lld` or replace it with `-fuse-ld=ld` I then get this error:

```console
$ clang++ noso-2m.cpp md5-c.cpp -o noso-2m -std=c++20 -O3 -DNDEBUG --stdlib=libc++ -lpthread -lc++abi -lncurses -lform -ltermcap
noso-2m.cpp:4:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
1 error generated.
```

I guess I need to `sudo apt install` the dev version of the package that supports `map` ?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @f04ever,

Okies, so after our talk on discord, we need to add these other 2 to the dependencies list:

- libc++-dev
- libc++abi-dev

And I'm guessing that suggesting the `clang` package name is also needed, right?

I'll also keep this one open until you complete the full list of minimal packages to make it compile on an Ubuntu system :smile: 

Cheers,
Gus

**Comment by f04ever** [comment]
Cheers!
